#!/bin/bash
mkdir curves
mkdir finalPlots
mkdir finalVis
mkdir finalVisBeforeRegisteration
mkdir rejected_badRatio
mkdir rejectedCurves
mkdir rejectedLandmakrs
mkdir rejected_notAllTeeth
mkdir rejected_notEnoughLandmarks
mkdir referenceFrames
mkdir referenceFrames/images
mkdir referenceFrames/labels
mkdir t1
mkdir t2
mkdir t3
mkdir t4
mkdir t5
mkdir t6
mkdir t7
mkdir t8